var synonyms = [['tuhaanu', 'tuhanu'], ['thonu', 'tuhanu'], ['asanu', 'saanu'], ['sanu', 'saanu'], ['ai', 'hai']];

var conversations_chatbot = [
    // [
    //     {q: 'greetings', a: 'sat sri akaal', ql: ['true', 'venerable', 'eternal'], al: ['sat', 'sri', 'akaal'], synonyms, match: 0.1 },
    //     {q: 'how are you doing?', a: 'ki haal hai ji?', ql: ['what', 'situation', 'is it', 'with-respect'], al: ['ki', 'haal', 'hai', 'ji'], synonyms, match: 0.1 },
    //     {q: 'it is a wonderful day', a: 'bada sohna din hai', ql: ['very', 'beautiful', 'day', 'it is'], al: ['bada', 'sohna', 'din', 'hai'], synonyms: [['bahut', 'bada']].concat(synonyms), match: 0.1 },
    //     {q: 'this is a wonderful place', a: 'badi sohni jagah hai', ql: ['very', 'beautiful', 'place', 'it is'], al: ['badi', 'sohni', 'jagah', 'hai'], synonyms: [['bahut', 'badi']].concat(synonyms), match: 0.1 },
    //     {q: "i am happy to meet ya'll", a: 'tuhanu mil ke bahut khushi hoi', ql: ["ya'll", 'after_meeting', 'very', 'happy', 'felt'], al: ['tuhanu', 'mil_ke', 'bahut', 'khushi', 'hoi'], synonyms: [['badi', 'bahut']].concat(synonyms), match: 0.1 },
    //     {q: 'we are here to recruit people', a: 'asi ithe aaye haan, saanu kamm lai bande chhidey ai', ql: ['we', 'here', 'come', 'ay', 'to us', 'work', 'for', 'people', 'need', 'ay'], al: ['asi', 'ithe', 'aaye', 'haan', 'saanu', 'kamm', 'lai', 'bande', 'chhidey', 'ai'], synonyms: synonyms, match: 0.1 },
    // ],
    // [
    //     {q: "Hi, how are you doing?", a: "Hā'i, tusīṁ kivēṁ hō?", ql: ["Hā'i,","tusīṁ","kivēṁ","hō?"], al: ["Hā'i,","tusīṁ","kivēṁ","hō?"], synonyms: [['tuhada', 'tuhaada']].concat(synonyms), match: 0.1},
    //     {q: "I'm doing great. How about you?", a: "Maiṁ vadhī'ā kara rihā hāṁ. Tuhāḍē bārē kivēṁ?", ql: ["Maiṁ","vadhī'ā","kara","rihā","hāṁ.","Tuhāḍē","bārē","kivēṁ?"], al: ["Maiṁ","vadhī'ā","kara","rihā","hāṁ.","Tuhāḍē","bārē","kivēṁ?"], synonyms: [['tuhada', 'tuhaada']].concat(synonyms), match: 0.1},
    //     {q: "Not too bad.", a: "Bahuta māṛā nahīṁ.", ql: ["Bahuta","māṛā","nahīṁ."], al: ["Bahuta","māṛā","nahīṁ."], synonyms: [['tuhada', 'tuhaada']].concat(synonyms), match: 0.1},
    //     {q: "Do you come to this restaurant often?", a: "Kī tusīṁ akasara isa raisaṭōraiṇṭa vica ā'undē hō?", ql: ["Kī","tusīṁ","akasara","isa","raisaṭōraiṇṭa","vica","ā'undē","hō?"], al: ["Kī","tusīṁ","akasara","isa","raisaṭōraiṇṭa","vica","ā'undē","hō?"], synonyms: [['tuhada', 'tuhaada']].concat(synonyms), match: 0.1},
    //     {q: "I've been here a couple of times, but I don't come on a regular basis. What have you been up to?", a: "Maiṁ ithē ka'ī vāra ā'i'ā hāṁ, para maiṁ niyamita taura'tē nahīṁ ā'undā. Tusīṁ kī karana ga'ē hō?", ql: ["Maiṁ","ithē","ka'ī","vāra","ā'i'ā","hāṁ,","para","maiṁ","niyamita","taura'tē","nahīṁ","ā'undā.","Tusīṁ","kī","karana","ga'ē","hō?"], al: ["Maiṁ","ithē","ka'ī","vāra","ā'i'ā","hāṁ,","para","maiṁ","niyamita","taura'tē","nahīṁ","ā'undā.","Tusīṁ","kī","karana","ga'ē","hō?"], synonyms: [['tuhada', 'tuhaada']].concat(synonyms), match: 0.1},
    //     {q: "I'm pretty busy at work these days, but otherwise, everything is great.", a: "Maiṁ ajakal'ha kama vica kāfī rujhi'ā hō'i'ā hāṁ, para nahīṁ tāṁ sabha kujha vadhī'ā hai.", ql: ["Maiṁ","ajakal'ha","kama","vica","kāfī","rujhi'ā","hō'i'ā","hāṁ,","para","nahīṁ","tāṁ","sabha","kujha","vadhī'ā","hai."], al: ["Maiṁ","ajakal'ha","kama","vica","kāfī","rujhi'ā","hō'i'ā","hāṁ,","para","nahīṁ","tāṁ","sabha","kujha","vadhī'ā","hai."], synonyms: [['tuhada', 'tuhaada']].concat(synonyms), match: 0.1},
    //     {q: "Well, have a good evening.", a: "Achā, cagī śāma hōvē.", ql: ["Achā,","cagī","śāma","hōvē."], al: ["Achā,","cagī","śāma","hōvē."], synonyms: [['tuhada', 'tuhaada']].concat(synonyms), match: 0.1},
    //     {q: "You too.", a: "Tusīṁ vī.", ql: ["Tusīṁ","vī."], al: ["Tusīṁ","vī."], synonyms: [['tuhada', 'tuhaada']].concat(synonyms), match: 0.1},
    // ],
	[
	    {
	        q: "How are you doing?",
	        a: "kiddan",
	        x: "how_is_it",
	        al: ["kiddan"],
	        ql: ["how_is_it"],
	        synonyms: [["kiddan","kidan"],["kiddan","kidaan"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Doing good",
	        a: "theek thaak",
	        x: "good goodie",
	        al: ["theek", "thaak"],
	        ql: ["good", "goodie"],
	        synonyms: [["theek","thik"],["thaak","thak"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "When did you get here?",
	        a: "kaddon aye",
	        x: "when arrived",
	        al: ["kaddon", "aye"],
	        ql: ["when", "arrived"],
	        synonyms: [["kaddon","kadon"],["aye","aaye"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Got here yesterday",
	        a: "kal aye si",
	        x: "yesterday arrived did",
	        al: ["kal", "aye", "si"],
	        ql: ["yesterday", "arrived", "did"],
	        synonyms: [["aye","aaye"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "When are you leaving?",
	        a: "kaddon jana",
	        x: "when leaving",
	        al: ["kaddon", "jana"],
	        ql: ["when", "leaving"],
	        synonyms: [["kaddon","kadon"],["jana","jaana"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Leaving tomorrow",
	        a: "kal jana",
	        x: "tomorrow leaving",
	        al: ["kal", "jana"],
	        ql: ["tomorrow", "leaving"],
	        synonyms: [["jana","jaana"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Okay good",
	        a: "theek hai",
	        x: "good is",
	        al: ["theek", "hai"],
	        ql: ["good", "is"],
	        synonyms: [["theek","thik"],["hai","ey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "See you later then",
	        a: "phir milde haan",
	        x: "again meet be",
	        al: ["phir", "milde", "haan"],
	        ql: ["again", "meet", "be"],
	        synonyms: [["haan","aan"],["haan","eyn"],].concat(synonyms),
	        match: 0.1,
	    },
	],
	[
	    {
	        q: "Hi, how are you doing?",
	        a: "hi, tusi kiven ho?",
	        x: "hi, y'all how are?",
	        al: ["hi", "tusi", "kiven", "ho"],
	        ql: ["hi", "y'all", "how", "are"],
	        synonyms: [["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["kiven","kive'n"],["kiven","kivey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'm doing great. How about you?",
	        a: "mein vadhia kara riha haan. tuhade bar'e kiven?",
	        x: "i good do occuring am. y'all about how?",
	        al: ["mein", "vadhia", "kara", "riha", "haan", "tuhade", "bar'e", "kiven"],
	        ql: ["i", "good", "do", "occuring", "am", "y'all", "about", "how"],
	        synonyms: [["mein","main"],["vadhia","vadi'a"],["vadhia","vadiya"],["kara","kar"],["riha","riha"],["haan","ha"],["haan","ha'n"],["tuhade","tuhaade"],["bar'e","barey"],["kiven","kive'n"],["kiven","kivey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Not too bad.",
	        a: "bahuta mara nahin.",
	        x: "too bad not.",
	        al: ["bahuta", "mara", "nahin"],
	        ql: ["too", "bad", "not"],
	        synonyms: [["bahuta","bahut"],["mara","mada"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Do you come to this restaurant often?",
	        a: "ki tusi aksar is restaurant vich aunde ho?",
	        x: "what y'all often this restaurant to come are?",
	        al: ["ki", "tusi", "aksar", "is", "restaurant", "vich", "aunde", "ho"],
	        ql: ["what", "y'all", "often", "this", "restaurant", "to", "come", "are"],
	        synonyms: [["ki","kee"],["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["is","iss"],["restaurant","raistoraint"],["vich","wich"],["aunde","aund'e"],["aunde","aundey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I've been here a couple of times, but I don't come on a regular basis. What have you been up to?",
	        a: "mein ithe kai vaari aia haan, par mein hamesha torte nahin aunda. tusi ki karan gae ho?",
	        x: "i here many times came am, but i regular basis not come. y'all what do went are?",
	        al: ["mein", "ithe", "kai", "vaari", "aia", "haan", "par", "mein", "hamesha", "torte", "nahin", "aunda", "tusi", "ki", "karan", "gae", "ho"],
	        ql: ["i", "here", "many", "times", "came", "am", "but", "i", "regular", "basis", "not", "come", "y'all", "what", "do", "went", "are"],
	        synonyms: [["mein","main"],["ithe","ith'e"],["ithe","ithey"],["kai","ka'i"],["vaari","vaar'i"],["aia","ai'a"],["aia","aiya"],["haan","ha"],["haan","ha'n"],["mein","main"],["torte","taur"],["torte","tau'r"],["torte","-te"],["torte","tey"],["aunda","aun'da"],["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["ki","kee"],["karan","kar'an"],["gae","gai"],["gae","ga'i"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'm pretty busy at work these days, but otherwise, everything is great.",
	        a: "mein ajkal kam vich kaafi rujhia hoia haan, par nahin taan sab kush vadhia hai.",
	        x: "i lately work to pretty busy keeping am, but not did every thing good is.",
	        al: ["mein", "ajkal", "kam", "vich", "kaafi", "rujhia", "hoia", "haan", "par", "nahin", "taan", "sab", "kush", "vadhia", "hai"],
	        ql: ["i", "lately", "work", "to", "pretty", "busy", "keeping", "am", "but", "not", "did", "every", "thing", "good", "is"],
	        synonyms: [["mein","main"],["kam","kamm"],["vich","wich"],["kaafi","kafi"],["kaafi","ka'fi"],["rujhia","rujhi'a"],["hoia","hoi'a"],["hoia","hoiya"],["haan","ha"],["haan","ha'n"],["taan","ta"],["taan","ta'an"],["sab","sabh"],["kush","kujh"],["vadhia","vadi'a"],["vadhia","vadiya"],["hai","ey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Well, have a good evening.",
	        a: "acha, changi shaam hove.",
	        x: "okay, good evening have.",
	        al: ["acha", "changi", "shaam", "hove"],
	        ql: ["okay", "good", "evening", "have"],
	        synonyms: [["acha","achha"],["changi","chang'i"],["shaam","sham"],["hove","hovey"],["hove","hov'e"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "You too.",
	        a: "tusi vi.",
	        x: "y'all too.",
	        al: ["tusi", "vi"],
	        ql: ["y'all", "too"],
	        synonyms: [["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],].concat(synonyms),
	        match: 0.1,
	    },
	],
	[
	    {
	        q: "It's nice to meet you. My name is Jack.",
	        a: "tuhanu mil ke ih changa lagia. mera naam jack hai.",
	        x: "you meet after this good felt. my name jack is.",
	        al: ["tuhanu", "mil", "ke", "ih", "changa", "lagia", "mera", "naam", "jack", "hai"],
	        ql: ["you", "meet", "after", "this", "good", "felt", "my", "name", "jack", "is"],
	        synonyms: [["tuhanu","tuhaanu"],["tuhanu","tuha'nu"],["ih","eh"],["lagia","lagiya"],["hai","ey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'm Steve. It's a pleasure to meet you.",
	        a: "mein steve haan. tuhanu mil ke khushi hoi.",
	        x: "i steve am. you meet after happiness felt.",
	        al: ["mein", "steve", "haan", "tuhanu", "mil", "ke", "khushi", "hoi"],
	        ql: ["i", "steve", "am", "you", "meet", "after", "happiness", "felt"],
	        synonyms: [["mein","main"],["haan","ha"],["haan","ha'n"],["tuhanu","tuhaanu"],["tuhanu","tuha'nu"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "What was (your) name again?",
	        a: "phir tuhada naam ki si?",
	        x: "again yours name what was?",
	        al: ["phir", "tuhada", "naam", "ki", "si"],
	        ql: ["again", "yours", "name", "what", "was"],
	        synonyms: [["phir","fir"],["tuhada","tuhaada"],["ki","kee"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Steve.",
	        a: "steve.",
	        x: "steve.",
	        al: ["steve"],
	        ql: ["steve"],
	        synonyms: [].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "So Steve, What do you do for a living?",
	        a: "ta steve, tusi kamm lai ki karde ho?",
	        x: "so steve, y'all living for what do are?",
	        al: ["ta", "steve", "tusi", "kamm", "lai", "ki", "karde", "ho"],
	        ql: ["so", "steve", "y'all", "living", "for", "what", "do", "are"],
	        synonyms: [["ta","ta'n"],["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["kamm","kam"],["ki","kee"],["karde","kard'e"],["karde","kardey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I work at the public library. How about you?",
	        a: "mein public library vich kam karda haan. tuhade bar'e kiven?",
	        x: "i public library to work doing am. y'all about how?",
	        al: ["mein", "public", "library", "vich", "kam", "karda", "haan", "tuhade", "bar'e", "kiven"],
	        ql: ["i", "public", "library", "to", "work", "doing", "am", "y'all", "about", "how"],
	        synonyms: [["mein","main"],["public","sarkari"],["public","janatak"],["library","kitaab_ghar"],["vich","wich"],["kam","kamm"],["karda","kard'a"],["haan","ha"],["haan","ha'n"],["tuhade","tuhaade"],["bar'e","barey"],["kiven","kive'n"],["kiven","kivey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'm a University student.",
	        a: "mein university da student haan.",
	        x: "i university of student am.",
	        al: ["mein", "university", "da", "student", "haan"],
	        ql: ["i", "university", "of", "student", "am"],
	        synonyms: [["mein","main"],["da","da'h"],["student","vidiarthi"],["haan","ha"],["haan","ha'n"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "That's great. It was nice meeting you.",
	        a: "ih bahuta vadhia hai. tuhanu mil ke ih changa lagia.",
	        x: "this too good is. you meet after this good felt.",
	        al: ["ih", "bahuta", "vadhia", "hai", "tuhanu", "mil", "ke", "ih", "changa", "lagia"],
	        ql: ["this", "too", "good", "is", "you", "meet", "after", "this", "good", "felt"],
	        synonyms: [["ih","eh"],["bahuta","bahut"],["vadhia","vadi'a"],["vadhia","vadiya"],["hai","ey"],["tuhanu","tuhaanu"],["tuhanu","tuha'nu"],["ih","eh"],["lagia","lagiya"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Yeah. It was a pleasure meeting you.",
	        a: "haan. ih tuhanu mil ke khushi hoi.",
	        x: "am. this you meet after happiness felt.",
	        al: ["haan", "ih", "tuhanu", "mil", "ke", "khushi", "hoi"],
	        ql: ["am", "this", "you", "meet", "after", "happiness", "felt"],
	        synonyms: [["haan","ha"],["haan","ha'n"],["ih","eh"],["tuhanu","tuhaanu"],["tuhanu","tuha'nu"],].concat(synonyms),
	        match: 0.1,
	    },
	],
	[
	    {
	        q: "Hey Jack, it's good to see you.",
	        a: "hi jack, tuhanu dekh ke changa lagia.",
	        x: "hey jack, you see after good felt.",
	        al: ["hi", "jack", "tuhanu", "dekh", "ke", "changa", "lagia"],
	        ql: ["hey", "jack", "you", "see", "after", "good", "felt"],
	        synonyms: [["hi","hey"],["hi","ey"],["hi","oye"],["tuhanu","tuhaanu"],["tuhanu","tuha'nu"],["lagia","lagiya"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Wow. How long has it been? It seems like more than a year. I'm doing pretty well. How about you?",
	        a: "vah. ih kina sama hoia hai? ih a saal toh vi more lagda hai. mein bahuta vadhia kara riha haan. tuhade bar'e kiven?",
	        x: "wow. this how time keeping is? this a year from too more seems is. i too good do occuring am. y'all about how?",
	        al: ["vah", "ih", "kina", "sama", "hoia", "hai", "ih", "a", "saal", "toh", "vi", "more", "lagda", "hai", "mein", "bahuta", "vadhia", "kara", "riha", "haan", "tuhade", "bar'e", "kiven"],
	        ql: ["wow", "this", "how", "time", "keeping", "is", "this", "a", "year", "from", "too", "more", "seems", "is", "i", "too", "good", "do", "occuring", "am", "y'all", "about", "how"],
	        synonyms: [["vah","vaah"],["ih","eh"],["kina","kinna"],["sama","samah"],["sama","sama'h"],["hoia","hoi'a"],["hoia","hoiya"],["hai","ey"],["ih","eh"],["toh","tohn"],["toh","to'n"],["lagda","lagdah"],["hai","ey"],["mein","main"],["bahuta","bahut"],["vadhia","vadi'a"],["vadhia","vadiya"],["kara","kar"],["riha","riha"],["haan","ha"],["haan","ha'n"],["tuhade","tuhaade"],["bar'e","barey"],["kiven","kive'n"],["kiven","kivey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Not too bad.",
	        a: "bahuta mara nahin.",
	        x: "too bad not.",
	        al: ["bahuta", "mara", "nahin"],
	        ql: ["too", "bad", "not"],
	        synonyms: [["bahuta","bahut"],["mara","mada"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "What movie did you come to see?",
	        a: "tusi kihdi movie dekhan aye ho?",
	        x: "y'all what movie watch came are?",
	        al: ["tusi", "kihdi", "movie", "dekhan", "aye", "ho"],
	        ql: ["y'all", "what", "movie", "watch", "came", "are"],
	        synonyms: [["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["kihdi","kihri"],["kihdi","kihrhi"],["kihdi","kihdhi"],["movie","film"],["movie","philam"],["dekhan","vekhan"],["aye","aaye"],["aye","aa'e"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I came here to see Matrix Revolution. How about you?",
	        a: "mein ithe matrix kranti vekhan aia haan. tuhade bar'e kiven?",
	        x: "i here matrix revolution watch came am. y'all about how?",
	        al: ["mein", "ithe", "matrix", "kranti", "vekhan", "aia", "haan", "tuhade", "bar'e", "kiven"],
	        ql: ["i", "here", "matrix", "revolution", "watch", "came", "am", "y'all", "about", "how"],
	        synonyms: [["mein","main"],["ithe","ith'e"],["ithe","ithey"],["vekhan","dekhan"],["aia","ai'a"],["aia","aiya"],["haan","ha"],["haan","ha'n"],["tuhade","tuhaade"],["bar'e","barey"],["kiven","kive'n"],["kiven","kivey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'm going to watch Finding Nemo.",
	        a: "mein nimo labhde vekhan ja riha haan.",
	        x: "i nimo finding watch going occuring am.",
	        al: ["mein", "nimo", "labhde", "vekhan", "ja", "riha", "haan"],
	        ql: ["i", "nimo", "finding", "watch", "going", "occuring", "am"],
	        synonyms: [["mein","main"],["labhde","bhalde"],["vekhan","dekhan"],["riha","riha"],["haan","ha"],["haan","ha'n"],].concat(synonyms),
	        match: 0.1,
	    },
	],
	[
	    {
	        q: "Hello",
	        a: "hello",
	        x: "hello",
	        al: ["hello"],
	        ql: ["hello"],
	        synonyms: [].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Hi Jane",
	        a: "hi jane",
	        x: "hi jane",
	        al: ["hi", "jane"],
	        ql: ["hi", "jane"],
	        synonyms: [].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Oh, hi Jill.",
	        a: "oh, hi jill.",
	        x: "oh, hi jill.",
	        al: ["oh", "hi", "jill"],
	        ql: ["oh", "hi", "jill"],
	        synonyms: [].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "What are you doing?",
	        a: "tusi ki kara rahe ho?",
	        x: "y'all what do doing are?",
	        al: ["tusi", "ki", "kara", "rahe", "ho"],
	        ql: ["y'all", "what", "do", "doing", "are"],
	        synonyms: [["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["ki","kee"],["kara","kar"],["rahe","rahey"],["rahe","rah'e"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'm doing the laundry.",
	        a: "mein laundry kara riha haan.",
	        x: "i laundry do occuring am.",
	        al: ["mein", "laundry", "kara", "riha", "haan"],
	        ql: ["i", "laundry", "do", "occuring", "am"],
	        synonyms: [["mein","main"],["laundry","landri"],["kara","kar"],["riha","riha"],["haan","ha"],["haan","ha'n"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'm so bored. I have nothing to do.",
	        a: "mein bahuta bore haan. merey kol karan lai kush nahin hai.",
	        x: "i too bore am. mine have do for thing not is.",
	        al: ["mein", "bahuta", "bore", "haan", "merey", "kol", "karan", "lai", "kush", "nahin", "hai"],
	        ql: ["i", "too", "bore", "am", "mine", "have", "do", "for", "thing", "not", "is"],
	        synonyms: [["mein","main"],["bahuta","bahut"],["bore","vehla"],["haan","ha"],["haan","ha'n"],["merey","mere"],["merey","mere'"],["kol","kole"],["karan","kar'an"],["kush","kujh"],["hai","ey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Why don't you come over and help me with the laundry?",
	        a: "tusi kiun nahin aunde ithe kapare dhona vich meri madad karde ho?",
	        x: "y'all why not come here clothes wash to my help do are?",
	        al: ["tusi", "kiun", "nahin", "aunde", "ithe", "kapare", "dhona", "vich", "meri", "madad", "karde", "ho"],
	        ql: ["y'all", "why", "not", "come", "here", "clothes", "wash", "to", "my", "help", "do", "are"],
	        synonyms: [["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["kiun","kiyon"],["aunde","aund'e"],["aunde","aundey"],["ithe","ithey"],["kapare","kaparey"],["kapare","kapade"],["kapare","kapadey"],["vich","wich"],["karde","kard'e"],["karde","kardey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'd rather do my own house chores. Hey, you wanna take a break from your house work and have coffee at Starbucks with me?",
	        a: "mein is di bajae apane khud de ghar de kamm nu karanga. hi, tusi apane ghar de kam toh break laina chahunde ho ithe merey naal starbucks wich coffee laina chahunde ho?",
	        x: "i this own rather our mine own home own work itself will_do. hey, y'all our home own work from break take want are here mine with starbucks at coffee take want are?",
	        al: ["mein", "is", "di", "bajae", "apane", "khud", "de", "ghar", "de", "kamm", "nu", "karanga", "hi", "tusi", "apane", "ghar", "de", "kam", "toh", "break", "laina", "chahunde", "ho", "ithe", "merey", "naal", "starbucks", "wich", "coffee", "laina", "chahunde", "ho"],
	        ql: ["i", "this", "own", "rather", "our", "mine", "own", "home", "own", "work", "itself", "will_do", "hey", "y'all", "our", "home", "own", "work", "from", "break", "take", "want", "are", "here", "mine", "with", "starbucks", "at", "coffee", "take", "want", "are"],
	        synonyms: [["mein","main"],["is","iss"],["bajae","bajaye"],["bajae","baja'e"],["apane","apney"],["kamm","kam"],["karanga","karunga"],["hi","hey"],["hi","ey"],["hi","oye"],["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["apane","apney"],["kam","kamm"],["toh","tohn"],["toh","to'n"],["break","chhutti"],["chahunde","chahundey"],["ithe","ithey"],["merey","mere"],["merey","mere'"],["wich","vich"],["coffee","kaupi"],["chahunde","chahundey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Sure, that sounds great. I'll meet you there in thirty minutes.",
	        a: "yakeenan, ih vadhia lag riha hai. mein tuhanu uthe teeh mintan vich milanga.",
	        x: "sure, this good feel occuring is. i you there thirty minutes to will_meet.",
	        al: ["yakeenan", "ih", "vadhia", "lag", "riha", "hai", "mein", "tuhanu", "uthe", "teeh", "mintan", "vich", "milanga"],
	        ql: ["sure", "this", "good", "feel", "occuring", "is", "i", "you", "there", "thirty", "minutes", "to", "will_meet"],
	        synonyms: [["yakeenan","bilkul"],["ih","eh"],["vadhia","vadi'a"],["vadhia","vadiya"],["riha","riha"],["hai","ey"],["mein","main"],["tuhanu","tuhaanu"],["tuhanu","tuha'nu"],["uthe","uthey"],["vich","wich"],["milanga","milunga"],].concat(synonyms),
	        match: 0.1,
	    },
	],
	[
	    {
	        q: "Hi Steve. What are you doing here?",
	        a: "hi steve. tusi ithe ki kara rahe ho?",
	        x: "hi steve. y'all here what do doing are?",
	        al: ["hi", "steve", "tusi", "ithe", "ki", "kara", "rahe", "ho"],
	        ql: ["hi", "steve", "y'all", "here", "what", "do", "doing", "are"],
	        synonyms: [["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["ithe","ith'e"],["ithe","ithey"],["ki","kee"],["kara","kar"],["rahe","rahey"],["rahe","rah'e"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'm meeting a friend here for dinner. How about you?",
	        a: "mein ithe a dosat nu raat de khane lai mil riha haan. tuhade bar'e kiven?",
	        x: "i here a friends itself night own meal for meet occuring am. y'all about how?",
	        al: ["mein", "ithe", "a", "dosat", "nu", "raat", "de", "khane", "lai", "mil", "riha", "haan", "tuhade", "bar'e", "kiven"],
	        ql: ["i", "here", "a", "friends", "itself", "night", "own", "meal", "for", "meet", "occuring", "am", "y'all", "about", "how"],
	        synonyms: [["mein","main"],["ithe","ith'e"],["ithe","ithey"],["khane","khaney"],["riha","riha"],["haan","ha"],["haan","ha'n"],["tuhade","tuhaade"],["bar'e","barey"],["kiven","kive'n"],["kiven","kivey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'm on my way home but I needed to stop by the book store to buy a text book.",
	        a: "mein ghar ja riha haan par mainu a shabad kitaab khareedan lai kitaab store duarey rukan di zaroorat si.",
	        x: "i home going occuring am but to_me a text book buy for book store at stop own need was.",
	        al: ["mein", "ghar", "ja", "riha", "haan", "par", "mainu", "a", "shabad", "kitaab", "khareedan", "lai", "kitaab", "store", "duarey", "rukan", "di", "zaroorat", "si"],
	        ql: ["i", "home", "going", "occuring", "am", "but", "to_me", "a", "text", "book", "buy", "for", "book", "store", "at", "stop", "own", "need", "was"],
	        synonyms: [["mein","main"],["riha","riha"],["haan","ha"],["haan","ha'n"],["mainu","meinu"],["store","dukaan"],["duarey","duare"],["zaroorat","lorh"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Didn't you finish school yet?",
	        a: "ki tusi aje school pura nahin keeta?",
	        x: "what y'all yet school finish not did?",
	        al: ["ki", "tusi", "aje", "school", "pura", "nahin", "keeta"],
	        ql: ["what", "y'all", "yet", "school", "finish", "not", "did"],
	        synonyms: [["ki","kee"],["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["aje","ajey"],["keeta","kita"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I have one more year, and then I'm done.",
	        a: "merey kol a hor saal hai, ithe phir mein pura ho gia.",
	        x: "mine have a more year is, here again i finish are over.",
	        al: ["merey", "kol", "a", "hor", "saal", "hai", "ithe", "phir", "mein", "pura", "ho", "gia"],
	        ql: ["mine", "have", "a", "more", "year", "is", "here", "again", "i", "finish", "are", "over"],
	        synonyms: [["merey","mere"],["merey","mere'"],["kol","kole"],["hor","hore"],["hai","ey"],["ithe","ithey"],["phir","fir"],["mein","main"],["gia","giya"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "What are you majoring in?",
	        a: "tusi kis vich major ho?",
	        x: "y'all which to major are?",
	        al: ["tusi", "kis", "vich", "major", "ho"],
	        ql: ["y'all", "which", "to", "major", "are"],
	        synonyms: [["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["vich","wich"],["major","pramukh"],["major","parmukh"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'm majoring in Sociology",
	        a: "mein samaaj shastar vich major haan",
	        x: "i social science to major am",
	        al: ["mein", "samaaj", "shastar", "vich", "major", "haan"],
	        ql: ["i", "social", "science", "to", "major", "am"],
	        synonyms: [["mein","main"],["vich","wich"],["major","pramukh"],["major","parmukh"],["haan","ha"],["haan","ha'n"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "How do you like your major?",
	        a: "tusi apane major nu kiven pasand karde ho?",
	        x: "y'all our major itself how like do are?",
	        al: ["tusi", "apane", "major", "nu", "kiven", "pasand", "karde", "ho"],
	        ql: ["y'all", "our", "major", "itself", "how", "like", "do", "are"],
	        synonyms: [["tusi","tussi"],["tusi","tusi'n"],["tusi","tussi'n"],["apane","apney"],["major","pramukh"],["major","parmukh"],["kiven","kive'n"],["kiven","kivey"],["karde","kard'e"],["karde","kardey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I really find the subject very interesting. I'm enjoying all my classes.",
	        a: "mainu sachmuch visha bahuta hi dilchasap lagda hai. mein apnian sarian classan da anand lei riha haan.",
	        x: "to_me really subject too much interesting seems is. i my all classes of joy get occuring am.",
	        al: ["mainu", "sachmuch", "visha", "bahuta", "hi", "dilchasap", "lagda", "hai", "mein", "apnian", "sarian", "classan", "da", "anand", "lei", "riha", "haan"],
	        ql: ["to_me", "really", "subject", "too", "much", "interesting", "seems", "is", "i", "my", "all", "classes", "of", "joy", "get", "occuring", "am"],
	        synonyms: [["mainu","meinu"],["sachmuch","sachi"],["visha","subject"],["bahuta","bahut"],["hi","he"],["lagda","lagdah"],["hai","ey"],["mein","main"],["apnian","apniyan"],["sarian","saarian"],["da","da'h"],["lei","lai"],["riha","riha"],["haan","ha"],["haan","ha'n"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "That's great.",
	        a: "ih bahuta vadhia hai.",
	        x: "this too good is.",
	        al: ["ih", "bahuta", "vadhia", "hai"],
	        ql: ["this", "too", "good", "is"],
	        synonyms: [["ih","eh"],["bahuta","bahut"],["vadhia","vadi'a"],["vadhia","vadiya"],["hai","ey"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "I'd better go now. I don't want to miss the bus.",
	        a: "mein hun chalia janda. mein bas nu khujhana nahin chahunda.",
	        x: "i now leave going. i bus itself miss not want.",
	        al: ["mein", "hun", "chalia", "janda", "mein", "bas", "nu", "khujhana", "nahin", "chahunda"],
	        ql: ["i", "now", "leave", "going", "i", "bus", "itself", "miss", "not", "want"],
	        synonyms: [["mein","main"],["chalia","chala"],["janda","jaanda"],["mein","main"],["khujhana","khujauna"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Alright, I'll talk to you later.",
	        a: "theek hai, mein tuhade naal baad vich gal karanga.",
	        x: "alright is, i y'all with later to talk will_do.",
	        al: ["theek", "hai", "mein", "tuhade", "naal", "baad", "vich", "gal", "karanga"],
	        ql: ["alright", "is", "i", "y'all", "with", "later", "to", "talk", "will_do"],
	        synonyms: [["hai","ey"],["mein","main"],["tuhade","tuhaade"],["vich","wich"],["gal","gall"],["karanga","karunga"],].concat(synonyms),
	        match: 0.1,
	    },
	    {
	        q: "Okay. See you later.",
	        a: "theek hai. baad vich milde haan.",
	        x: "alright is. later to meet am.",
	        al: ["theek", "hai", "baad", "vich", "milde", "haan"],
	        ql: ["alright", "is", "later", "to", "meet", "am"],
	        synonyms: [["hai","ey"],["vich","wich"],["milde","mildey"],["haan","ha"],["haan","ha'n"],].concat(synonyms),
	        match: 0.1,
	    },
	],
];
